"""feat(auth): agregar campo cedula y estado de activacion (is_active=False) en users

Revision ID: 22d7d68f4844
Revises: c48e057bd4cd
Create Date: 2026-06-15 15:20:35.693163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d7d68f4844'
down_revision: Union[str, Sequence[str], None] = 'c48e057bd4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cedula', sa.String(length=13), nullable=False))
    op.create_index(op.f('ix_users_cedula'), 'users', ['cedula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cedula'), table_name='users')
    op.drop_column('users', 'cedula')
    # ### end Alembic commands ###
