trigger: none # Apagado para push directos

pr:
  branches:
    include:
      - develop
      - staging
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:

  pythonVersion: '3.14'

steps:
  - task: UsePythonVersion@0
    displayName: 'Configurar versión de Python'
    inputs:
      versionSpec: '$(pythonVersion)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Instalar dependencias (requirements.txt)'

  - script: |
      pytest -v
    displayName: 'Compuerta de Calidad: Ejecutar Pruebas Unitarias (Pytest)'
    env:
      DATABASE_URL: "sqlite+aiosqlite:///:memory:"
      JWT_SECRET_KEY: "super_secreto_ficticio_para_el_ci_pipeline"